ae_type: 'SelfSupervisedAE'
base_data_path: './dataset/data'
save_path: './logs/self_supervised'

train_params:
  device: cuda
  optimizer:
    name: Adam
    lr: 0.0001
  steps: 50000

train_dl_params:
  batch_size: 32
  shuffle: True
  drop_last: True

val_dl_params:
  batch_size: 32
  shuffle: False
  drop_last: False


model_kwargs:
  conv_block1:
    op1: [3, 32]
    op2: [32, 32]
    op3: [32, 32]
  conv_block2:
    op1: [32, 64]
    op2: [64, 64]
    op3: [64, 64]

  encoding_size: 4096 # 8 * 8 * 64
  n_hiddens: 128
